import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs/promises';
import * as data from '../dist/data.js';
import {translate} from '../dist/i18n.js';
import {webcrypto} from 'node:crypto';
const source=(await fs.readFile(new URL('../dist/app.js',import.meta.url),'utf8')).replace(/^import .*;\r?\n/gm,'').replace(/\n(?:render|boot)\(\);\s*$/,'');
function harness(role='teacher',id='t1',teacherId='t1'){
const memory=new Map(),storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
const ctx=vm.createContext({...data,persist:db=>storage.setItem('science-lab-v1',JSON.stringify(db)),esc:data.escapeHTML,translate,console,crypto:webcrypto,structuredClone,Intl,Date,JSON,URL,Blob,TextEncoder,localStorage:storage,sessionStorage:storage,location:{hash:''},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return []}},window:{addEventListener(){}},setTimeout(){},clearInterval(){},setInterval(){}});
vm.runInContext(source,ctx);
vm.runInContext('session='+JSON.stringify({role,id,teacherId,demo:true}),ctx);
return {run:code=>vm.runInContext(code,ctx),ctx};
}
test('fee totals respect multi-batch enrollment, period and partial payments',()=>{const db=data.seed();assert.equal(data.outstanding(db,'s1'),1200);db.payments.push({studentId:'s1',batchId:'b2',month:data.month(),amount:500});assert.equal(data.outstanding(db,'s1'),700);assert.equal(data.outstanding(db,'s1','2000-01'),2700);db.batches[1].status='Archived';assert.equal(data.outstanding(db,'s1'),0);});
test('grading handles exact thresholds, custom scales, and absence',()=>{assert.equal(data.grade(80),'A+');assert.equal(data.grade(79),'A');assert.equal(data.grade(32),'F');assert.equal(data.grade(50,'60:Pass,0:Fail'),'Fail');assert.equal(data.attendanceRate([]),0);assert.equal(data.attendanceRate([{status:'Present'},{status:'Absent'},{status:'Late'}]),67);});
test('HTML and CSV escape user content and spreadsheet formulas',()=>{assert.equal(data.escapeHTML('<script>"&'), '&lt;script&gt;&quot;&amp;');const c=data.csv([['=SUM(1,2)','a"b','line\nbreak']]);assert.ok(c.includes("'=SUM"));assert.ok(c.includes('a""b'));});
test('every allowed route renders for all roles in both languages',()=>{for(const [role,id,teacherId] of [['teacher','t1','t1'],['teacher','t2','t2'],['student','s1','t1'],['admin','admin',null]]){const h=harness(role,id,teacherId);for(const language of ['en','bn']){h.run('db.settings.language='+JSON.stringify(language));const pages=h.run('Object.keys(labels).filter(allowed)');for(const page of pages){const html=h.run('page='+JSON.stringify(page)+';renderFeaturePage()');assert.ok(html.includes('<h1>'),role+':'+page);assert.ok(!html.includes('undefined'),role+':'+page+' leaked undefined');}}}});
test('student sees only own attendance, marks, payments, submissions, published exams and enrolled content',()=>{const h=harness('student','s1','t1');for(const key of ['attendance','marks','payments','submissions'])assert.equal(h.run('visible('+JSON.stringify(key)+').every(r=>r.studentId==="s1")'),true);assert.equal(h.run('visible("students").length'),1);assert.equal(h.run('visible("exams").some(r=>r.status==="Draft")'),false);assert.equal(h.run('visible("assignments").some(r=>r.batchId==="b3")'),false);assert.equal(h.run('allowed("students")'),false);assert.equal(h.run('canEditEntity("payments")'),false);});
test('second teacher cannot see first teacher records and disabled modules are gated',()=>{const h=harness('teacher','t2','t2');assert.equal(h.run('visible("students").length'),0);assert.equal(h.run('visible("messages").length'),0);assert.equal(h.run('allowed("ai")'),false);assert.equal(h.run('allowed("messages")'),false);assert.equal(h.run('canAccessRecord("students",db.students[0])'),false);});
test('validation rejects duplicate IDs, missing guardian, overpayment, bad marks and schedule overlap',()=>{const h=harness();assert.throws(()=>h.run('validateRecord("students",{id:"new",studentId:"SL-1001",guardianPhone:"01711111111",batchIds:["b1"]},null)'),/already exists/);assert.throws(()=>h.run('validateRecord("students",{guardianPhone:"abc"},null)'),/phone/);assert.throws(()=>h.run('validateRecord("payments",{studentId:"s1",batchId:"b1",month:month(),amount:1},null)'),/exceeds/);assert.throws(()=>h.run('validateRecord("exams",{total:10,pass:11},null)'),/marks/);assert.throws(()=>h.run('validateRecord("routine",{id:"new",day:new Date().getDay(),start:"16:30",end:"17:30"},null)'),/overlaps/);});
test('teacher export does not include another teacher or platform account',()=>{const h=harness();assert.equal(h.run('scopedBackup().teachers.length'),1);assert.equal(h.run('scopedBackup().students.every(s=>s.teacherId==="t1")'),true);});
test('standard student CSV omits guardian contacts',()=>{const h=harness();h.run('download=(name,text)=>globalThis.exported=text;exportEntity("students")');assert.ok(!h.ctx.exported.includes('Guardian'));assert.ok(!h.ctx.exported.includes('01711111111'));});
test('Back exits demo teacher preview to Super Admin',async()=>{const h=harness();h.run('render=()=>{};closeModal=()=>{};session.impersonating=true');await h.run('featureAction("back")');assert.equal(h.run('session.role'),'admin');assert.equal(h.run('!!session.impersonating'),false);});

test('ZIP output has valid records, unicode filenames and exact content',async()=>{const {zipFiles}=await import('../dist/zip.js');const bytes=new Uint8Array(await(await zipFiles([{name:'শিক্ষার্থী/answer.txt',data:'F = ma'},{name:'note.txt',data:'Hello'}])).arrayBuffer());const dv=new DataView(bytes.buffer);assert.equal(dv.getUint32(0,true),0x04034b50);assert.equal(dv.getUint16(6,true),0x800);const len=dv.getUint16(26,true),size=dv.getUint32(18,true);assert.equal(new TextDecoder().decode(bytes.slice(30,30+len)),'শিক্ষার্থী/answer.txt');assert.equal(new TextDecoder().decode(bytes.slice(30+len,30+len+size)),'F = ma');assert.equal(dv.getUint32(bytes.length-22,true),0x06054b50);assert.equal(dv.getUint16(bytes.length-12,true),2);});
test('AI and guardian adapters fail explicitly until a provider is connected',async()=>{const {runAgent,sendGuardianMessage}=await import('../dist/integrations.js');await assert.rejects(runAgent(),/not connected/);await assert.rejects(sendGuardianMessage(),/not connected/);});
test('expired subscriptions are suspended locally after the grace period',()=>{const h=harness();h.run('db.teachers[0].expiry="2000-01-01";evaluateLocalLifecycle()');assert.equal(h.run('db.teachers[0].status'),'Suspended');assert.equal(h.run('db.audit[0].action'),'Suspend');});

test('CSV import parser preserves quoted commas, quotes, multiline fields and rejects malformed input',()=>{const h=harness();assert.equal(h.run('parseCSV(\'name,address\\n"Ayesha","Dhaka, Bangladesh"\')[1][1]'),'Dhaka, Bangladesh');assert.equal(h.run('parseCSV(\'name\\n"A ""quoted"" name"\')[1][0]'),'A "quoted" name');assert.equal(h.run('parseCSV(\'name\\n"line1\\nline2"\')[1][0]'),'line1\nline2');assert.throws(()=>h.run('parseCSV(\'"broken\')'),/Unclosed/);});
test('individual notices remain invisible to other students',()=>{const h=harness('student','s1','t1');h.run('db.notices.push({id:"private",teacherId:"t1",studentId:"s2",batchId:"all",title:"Private"})');assert.equal(h.run('visible("notices").some(n=>n.id==="private")'),false);});
test('group chat restricts enrolled students to teacher announcements unless discussion enabled',()=>{const h=harness('student','s1','t1');h.run('chatStudent="group-b1"');assert.ok(h.run('messagesPage()').includes('Only your teacher can post here.'));assert.ok(!h.run('messagesPage()').includes('id="chat-form"'));h.run('db.batches[0].discussion=true');assert.ok(h.run('messagesPage()').includes('id="chat-form"'));assert.ok(!h.run('messagesPage()').includes('group-b3'));});
test('combined report uses the latest published exam per subject',()=>{const h=harness();h.run('modal=(title,body)=>{globalThis.capturedReport=body}; db.exams.push({id:"chem",teacherId:"t1",batchId:"b2",subject:"Chemistry",title:"Chemistry test",date:today(),total:100,status:"Published"});db.marks.push({id:"chem-m",teacherId:"t1",examId:"chem",studentId:"s1",marks:85});combinedReport("s1")');const report=h.run('capturedReport');assert.ok(report.includes('Chemistry test'));assert.ok(report.includes('Physics · Chapter 03'));assert.ok(!report.includes('Physics · Chapter 01'));});

test('dashboard shortcuts respect roles and expose keyboard-operable chart and attendance controls',()=>{
 const teacher=harness(),student=harness('student','s1','t1');
 const html=teacher.run('dashboard()');assert.ok(html.includes('data-go="students"'));assert.ok(html.includes('data-action="pulse-exam:'));assert.ok(html.includes('tabindex="0"'));assert.ok(html.includes('data-action="attendance-breakdown:Absent"'));assert.ok(!html.includes('Ayesha Rahman · Physics'));
 assert.ok(student.run("stat('Active batches','2','','batches')").includes('data-go="routine"'));assert.ok(!student.run("stat('Active batches','2','','batches')").includes('data-go="batches"'));
});
test('student chart detail includes only own visible marks',async()=>{
 const h=harness('student','s1','t1');h.run('modal=(title,body)=>{globalThis.detailBody=body};');
 await h.run("featureAction('pulse-exam:'+visible('exams').find(e=>e.status==='Published').id)");
 assert.ok(h.run('detailBody').includes('Ayesha Rahman'));assert.ok(!h.run('detailBody').includes('Arif Hasan'));
});

test('only Super Admin can open API connections or see its AI shortcut',()=>{for(const role of ['teacher','student']){const h=harness(role,role==='teacher'?'t1':'s1','t1');assert.equal(h.run("allowed('connections')"),false);assert.ok(!h.run('aiPage()').includes('go:connections'));assert.ok(!h.run('connectionsPage()').includes('service-form'));}const h=harness('admin','admin',null);assert.equal(h.run("allowed('connections')"),true);});
